name: barg_test
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  get: ^4.6.1
  get_it: ^7.2.0
  mockito: ^5.1.0
  shimmer_animation: ^2.1.0+1
  dartz: ^0.10.1
  email_validator: ^2.0.1
  flutter_spinkit: ^5.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.5
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/
    - assets/images/

  fonts:
    - family: RooneySans
      fonts:
        - asset: assets/fonts/RooneySansRegular.OTF

